spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.33.1:9092
      group-id: myGroup
      auto-offset-reset: earliest
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
